version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:3001"
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend/awstraining
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-net
    depends_on:
      - backend
      - user-service

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "3003:3003"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
